# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some other blog of benjdewantara
email: ben.manullang@students.itb.ac.id
description: > # this means to ignore newlines until "baseurl:"
  Work on this later..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benjdewantara.github.io" # the base hostname & protocol for your site
twitter_username: benjdewantara
github_username:  benjdewantara

# Build settings
markdown: kramdown
highlighter: rouge
#highlighter: pygment
